"""
LastHorizon — shared Blender helpers for procedural asset generation.

Every asset in `public/assets/models/` is generated by the scripts in this
folder. Nothing is downloaded, imported or traced from any third party source.

Run inside Blender (via Blender MCP or `blender --background --python`):

    exec(open("<repo>/scripts/blender/build_all.py").read())

Conventions
-----------
* Blender is Z-up; the glTF exporter converts to Y-up for Three.js.
* Characters and directional props face **-Y in Blender**, which becomes
  **+Z in glTF/Three.js**. `rotation.y = atan2(dir.x, dir.z)` then works.
* Colours in `PALETTE` are authored in sRGB and converted to linear on
  material creation so the exported baseColorFactor renders as authored.
* One material per colour, shared across every object, so the Three.js
  AssetManager can collapse them into a small set of toon materials.
"""

import bpy
import bmesh
import math
import os
import random
from mathutils import Vector, Euler, Matrix  # noqa: F401  (Matrix used by callers)

# --------------------------------------------------------------------------
# Paths
# --------------------------------------------------------------------------

REPO_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
) if "__file__" in dir() else "C:/Users/awaiz/OneDrive/Desktop/LastHorizon"

MODEL_DIR = os.path.join(REPO_ROOT, "public", "assets", "models").replace("\\", "/")


def ensure_model_dir():
    os.makedirs(MODEL_DIR, exist_ok=True)
    return MODEL_DIR


# --------------------------------------------------------------------------
# Colour
# --------------------------------------------------------------------------

def srgb_to_linear(c):
    if c <= 0.04045:
        return c / 12.92
    return ((c + 0.055) / 1.055) ** 2.4


def hex_to_srgb(h):
    h = h.lstrip("#")
    return (int(h[0:2], 16) / 255.0, int(h[2:4], 16) / 255.0, int(h[4:6], 16) / 255.0)


# Art-directed palette. Warm, slightly desaturated Mediterranean summer.
PALETTE = {
    # character
    "skin":         "#F2CBA8",
    "hair":         "#2E2420",
    "hat_straw":    "#DCC177",
    "hat_band":     "#B79A54",
    "shirt":        "#EFEDE2",
    "shirt_shade":  "#DBD8C9",
    "shorts":       "#8A9455",
    "shoe":         "#9C7F5E",
    "eye":          "#2A2320",

    # architecture
    "wall_mauve":   "#B99A9A",
    "wall_pink":    "#C9AFAF",
    "wall_cream":   "#E7D7B0",
    "wall_sand":    "#D8C6A0",
    "wall_grey":    "#A89494",
    "roof_red":     "#B8474F",
    "roof_orange":  "#CE5C3C",
    "roof_dark":    "#6E4038",
    "roof_under":   "#5E453C",
    "trim_white":   "#E9E4D6",
    "window_glass": "#5E7A80",
    "window_frame": "#C6BCA8",
    "door_navy":    "#4B4A70",
    "door_wood":    "#8A6F4E",
    "vent_grey":    "#B0A896",
    "concrete":     "#C8C2B4",
    "concrete_dk":  "#A9A395",
    "metal_grey":   "#9EA3A2",
    "metal_light":  "#C9CCC9",
    "solar_panel":  "#4A5570",
    "solar_frame":  "#8E96A6",
    "wood_plank":   "#8A6F4E",
    "wood_light":   "#B79A6A",
    "wood_pole":    "#6B5A44",
    "pole_dark":    "#4A4640",
    "lamp_head":    "#5A554C",
    "lamp_glass":   "#F5EBC8",
    "barrier_wood": "#C79A4E",

    # nature
    "leaf_dark":    "#2B564A",
    "leaf_mid":     "#3E7A66",
    "leaf_light":   "#63A47C",
    "leaf_teal":    "#33685A",
    "palm_frond":   "#2E4F3A",
    "trunk_brown":  "#6F5A44",
    "trunk_grey":   "#8A7A66",
    "bush_dark":    "#2F5A4C",
    "bush_mid":     "#4A7D62",
    "rock_light":   "#CFC8B8",
    "rock_dark":    "#4C5B51",
    "rock_mid":     "#9AA093",
    "grass_green":  "#93B87C",
    "grass_dry":    "#C4BE8A",

    # collectibles
    "paper_white":  "#F4F1E6",
    "boat_red":     "#C9584B",
    "boat_wood":    "#C7A16A",
    "chime_wood":   "#9A7B52",
    "chime_metal":  "#CBC3A6",
    "camera_body":  "#4E4A46",
    "camera_metal": "#B9B4A6",
    "star_gold":    "#E7C266",
}

_MATERIAL_CACHE = {}


def mk_material(key):
    """Create (or fetch) a shared material for a palette key or raw hex."""
    if key in _MATERIAL_CACHE:
        return _MATERIAL_CACHE[key]

    hexcode = PALETTE.get(key, key)
    r, g, b = hex_to_srgb(hexcode)
    lin = (srgb_to_linear(r), srgb_to_linear(g), srgb_to_linear(b), 1.0)

    mat = bpy.data.materials.new(name=key if key in PALETTE else "c" + hexcode.lstrip("#"))
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    if bsdf:
        bsdf.inputs["Base Color"].default_value = lin
        bsdf.inputs["Roughness"].default_value = 0.85
        bsdf.inputs["Metallic"].default_value = 0.0
    mat.diffuse_color = lin
    _MATERIAL_CACHE[key] = mat
    return mat


def clear_material_cache():
    _MATERIAL_CACHE.clear()


# --------------------------------------------------------------------------
# Scene management
# --------------------------------------------------------------------------

def reset_scene():
    """Wipe every datablock so each asset build starts from a clean slate."""
    if bpy.context.object and bpy.context.object.mode != "OBJECT":
        bpy.ops.object.mode_set(mode="OBJECT")

    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)

    # Actions are kept alive by fake users; drop those first or a rebuild
    # accumulates "Walk.001", "Walk.002", ... and the exporter emits them all.
    for act in bpy.data.actions:
        act.use_fake_user = False

    for coll in (bpy.data.objects, bpy.data.meshes, bpy.data.materials,
                 bpy.data.armatures, bpy.data.actions, bpy.data.curves):
        for block in list(coll):
            if block.users == 0:
                coll.remove(block)

    clear_material_cache()
    bpy.context.scene.frame_set(1)


# --------------------------------------------------------------------------
# Primitive builders  (all return a fresh object, flat shaded by default)
# --------------------------------------------------------------------------

def _finish(obj, mat_key, flat=True):
    if mat_key is not None:
        obj.data.materials.append(mk_material(mat_key))
    if flat:
        for poly in obj.data.polygons:
            poly.use_smooth = False
    return obj


def mesh_from(name, verts, faces, mat_key=None, flat=True):
    me = bpy.data.meshes.new(name)
    me.from_pydata(verts, [], faces)
    me.update()
    obj = bpy.data.objects.new(name, me)
    bpy.context.collection.objects.link(obj)
    return _finish(obj, mat_key, flat)


def box(name, size, center=(0, 0, 0), mat_key=None):
    """Axis-aligned box. `size` is the full extent on each axis."""
    sx, sy, sz = size[0] / 2.0, size[1] / 2.0, size[2] / 2.0
    cx, cy, cz = center
    v = [
        (cx - sx, cy - sy, cz - sz), (cx + sx, cy - sy, cz - sz),
        (cx + sx, cy + sy, cz - sz), (cx - sx, cy + sy, cz - sz),
        (cx - sx, cy - sy, cz + sz), (cx + sx, cy - sy, cz + sz),
        (cx + sx, cy + sy, cz + sz), (cx - sx, cy + sy, cz + sz),
    ]
    # Wound counter-clockwise seen from outside so normals point out and the
    # meshes survive backface culling in Three.js.
    f = [(3, 2, 1, 0), (4, 5, 6, 7), (0, 1, 5, 4),
         (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]
    return mesh_from(name, v, f, mat_key)


def wedge(name, size, center=(0, 0, 0), mat_key=None, axis="y"):
    """Right-triangle prism — ramps, shed roofs, awnings.

    axis="y": full height at -Y, sloping down toward +Y.
    axis="x": full height at -X, sloping down toward +X.
    """
    sx, sy, sz = size[0] / 2.0, size[1] / 2.0, size[2] / 2.0
    cx, cy, cz = center
    base = [
        (cx - sx, cy - sy, cz - sz), (cx + sx, cy - sy, cz - sz),
        (cx + sx, cy + sy, cz - sz), (cx - sx, cy + sy, cz - sz),
    ]
    if axis == "y":
        v = base + [(cx - sx, cy - sy, cz + sz), (cx + sx, cy - sy, cz + sz)]
        f = [(3, 2, 1, 0), (0, 1, 5, 4), (4, 5, 2, 3), (0, 4, 3), (1, 2, 5)]
    else:
        v = base + [(cx - sx, cy - sy, cz + sz), (cx - sx, cy + sy, cz + sz)]
        f = [(3, 2, 1, 0), (0, 4, 5, 3), (5, 4, 1, 2), (0, 1, 4), (3, 5, 2)]
    return mesh_from(name, v, f, mat_key)


def gable_roof(name, width, depth, height, center=(0, 0, 0), overhang=0.0,
               ridge_along="y", mat_key=None, thickness=0.0):
    """Classic pitched roof. Ridge runs along Y (default) or X."""
    cx, cy, cz = center
    w = width / 2.0 + overhang
    d = depth / 2.0 + overhang
    if ridge_along == "y":
        v = [
            (cx - w, cy - d, cz), (cx + w, cy - d, cz),
            (cx + w, cy + d, cz), (cx - w, cy + d, cz),
            (cx, cy - d, cz + height), (cx, cy + d, cz + height),
        ]
        f = [(0, 1, 2, 3), (0, 4, 5, 3), (1, 5, 4), (2, 5, 1), (0, 3, 5, 4)]
        f = [(3, 2, 1, 0), (0, 1, 4), (1, 2, 5, 4), (2, 3, 5), (3, 0, 4, 5)]
    else:
        v = [
            (cx - w, cy - d, cz), (cx + w, cy - d, cz),
            (cx + w, cy + d, cz), (cx - w, cy + d, cz),
            (cx - w, cy, cz + height), (cx + w, cy, cz + height),
        ]
        f = [(3, 2, 1, 0), (0, 1, 5, 4), (1, 2, 5), (2, 3, 4, 5), (3, 0, 4)]
    obj = mesh_from(name, v, f, mat_key)
    if thickness > 0:
        sol = obj.modifiers.new("solid", "SOLIDIFY")
        sol.thickness = thickness
        sol.offset = -1
    return obj


def cylinder(name, radius, height, verts=12, center=(0, 0, 0), mat_key=None,
             radius_top=None, cap=True):
    rt = radius if radius_top is None else radius_top
    cx, cy, cz = center
    v, f = [], []
    for i in range(verts):
        a = 2 * math.pi * i / verts
        v.append((cx + math.cos(a) * radius, cy + math.sin(a) * radius, cz))
    for i in range(verts):
        a = 2 * math.pi * i / verts
        v.append((cx + math.cos(a) * rt, cy + math.sin(a) * rt, cz + height))
    for i in range(verts):
        j = (i + 1) % verts
        f.append((i, j, verts + j, verts + i))
    if cap:
        f.append(tuple(range(verts - 1, -1, -1)))
        f.append(tuple(range(verts, verts * 2)))
    return mesh_from(name, v, f, mat_key)


def tube_along(name, points, radius, verts=8, mat_key=None, taper=None):
    """Sweep a circular profile along a polyline — poles, cables, branches."""
    v, f = [], []
    n = len(points)
    for idx, p in enumerate(points):
        p = Vector(p)
        if idx < n - 1:
            fwd = (Vector(points[idx + 1]) - p).normalized()
        else:
            fwd = (p - Vector(points[idx - 1])).normalized()
        if idx > 0:
            prev = (p - Vector(points[idx - 1])).normalized()
            fwd = (fwd + prev).normalized()
        up = Vector((0, 0, 1))
        if abs(fwd.dot(up)) > 0.99:
            up = Vector((1, 0, 0))
        side = fwd.cross(up).normalized()
        up2 = side.cross(fwd).normalized()
        r = radius if taper is None else radius * taper(idx / max(1, n - 1))
        for i in range(verts):
            # negative sweep so the profile runs counter-clockwise about the
            # forward axis, which makes the quad windings below face outward
            a = -2 * math.pi * i / verts
            v.append(tuple(p + side * (math.cos(a) * r) + up2 * (math.sin(a) * r)))
    for s in range(n - 1):
        for i in range(verts):
            j = (i + 1) % verts
            a0 = s * verts + i
            b0 = s * verts + j
            a1 = (s + 1) * verts + i
            b1 = (s + 1) * verts + j
            f.append((a0, b0, b1, a1))
    f.append(tuple(range(verts - 1, -1, -1)))
    f.append(tuple(range((n - 1) * verts, n * verts)))
    return mesh_from(name, v, f, mat_key)


def ico_blob(name, radius, center=(0, 0, 0), subdiv=2, jitter=0.18, seed=0,
             scale=(1, 1, 1), mat_key=None, flatten_bottom=None):
    """Faceted organic mass — tree canopies, bushes, rocks, clouds."""
    rng = random.Random(seed)
    bm = bmesh.new()
    bmesh.ops.create_icosphere(bm, subdivisions=subdiv, radius=radius)
    for vert in bm.verts:
        d = vert.co.normalized()
        vert.co += d * (rng.uniform(-jitter, jitter) * radius)
        vert.co.x *= scale[0]
        vert.co.y *= scale[1]
        vert.co.z *= scale[2]
        if flatten_bottom is not None and vert.co.z < flatten_bottom:
            vert.co.z = flatten_bottom + (vert.co.z - flatten_bottom) * 0.15
    me = bpy.data.meshes.new(name)
    bm.to_mesh(me)
    bm.free()
    obj = bpy.data.objects.new(name, me)
    bpy.context.collection.objects.link(obj)
    obj.location = center
    return _finish(obj, mat_key)


def plane(name, width, depth, center=(0, 0, 0), mat_key=None):
    w, d = width / 2.0, depth / 2.0
    cx, cy, cz = center
    v = [(cx - w, cy - d, cz), (cx + w, cy - d, cz), (cx + w, cy + d, cz), (cx - w, cy + d, cz)]
    return mesh_from(name, v, [(0, 1, 2, 3)], mat_key)


# --------------------------------------------------------------------------
# Object utilities
# --------------------------------------------------------------------------

def bevel(obj, width=0.012, segments=1, angle=math.radians(50)):
    m = obj.modifiers.new("bevel", "BEVEL")
    m.width = width
    m.segments = segments
    m.limit_method = "ANGLE"
    m.angle_limit = angle
    m.harden_normals = False
    return obj


def apply_modifiers(obj):
    bpy.context.view_layer.objects.active = obj
    for m in list(obj.modifiers):
        try:
            bpy.ops.object.modifier_apply(modifier=m.name)
        except RuntimeError:
            obj.modifiers.remove(m)
    return obj


def rotate_verts(obj, angles, pivot=(0, 0, 0)):
    """Bake an XYZ rotation (radians) into the mesh, about a world pivot.

    Setting `obj.rotation_euler` pivots about the object origin, which for
    every primitive here sits at the world origin — so a part authored at
    z=4 would swing metres away. Baking into the vertices avoids that trap.
    """
    r = Euler(angles, "XYZ").to_matrix()
    piv = Vector(pivot)
    for v in obj.data.vertices:
        v.co = r @ (v.co - piv) + piv
    return obj


def transform(obj, loc=None, rot=None, scale=None):
    if loc is not None:
        obj.location = loc
    if rot is not None:
        obj.rotation_euler = Euler(rot, "XYZ")
    if scale is not None:
        obj.scale = scale if hasattr(scale, "__len__") else (scale, scale, scale)
    return obj


def join_objects(objs, name):
    """Join a list of mesh objects into one, applying modifiers first."""
    objs = [o for o in objs if o is not None]
    if not objs:
        return None
    bpy.ops.object.select_all(action="DESELECT")
    for o in objs:
        apply_modifiers(o)
    for o in objs:
        o.select_set(True)
    bpy.context.view_layer.objects.active = objs[0]
    if len(objs) > 1:
        bpy.ops.object.join()
    result = bpy.context.view_layer.objects.active
    result.name = name
    result.data.name = name + "_mesh"
    bpy.ops.object.select_all(action="DESELECT")
    return result


def set_origin_to(obj, point=(0, 0, 0)):
    """Move the mesh so that `point` (world) becomes the object origin."""
    mw = obj.matrix_world.copy()
    offset = Vector(point)
    me = obj.data
    for v in me.vertices:
        v.co = mw @ v.co - offset
    obj.matrix_world = Matrix.Translation(offset)
    return obj


def recalc_normals(obj):
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.select_all(action="DESELECT")
    obj.select_set(True)
    bpy.ops.object.mode_set(mode="EDIT")
    bpy.ops.mesh.select_all(action="SELECT")
    bpy.ops.mesh.normals_make_consistent(inside=False)
    bpy.ops.object.mode_set(mode="OBJECT")
    bpy.ops.object.select_all(action="DESELECT")
    return obj


def tri_count(obj):
    obj.data.calc_loop_triangles()
    return len(obj.data.loop_triangles)


# --------------------------------------------------------------------------
# Export
# --------------------------------------------------------------------------

def export_glb(objs, filename, animations=False):
    """Export the given objects to public/assets/models/<filename>."""
    ensure_model_dir()
    path = os.path.join(MODEL_DIR, filename).replace("\\", "/")

    if bpy.context.object and bpy.context.object.mode != "OBJECT":
        bpy.ops.object.mode_set(mode="OBJECT")
    bpy.ops.object.select_all(action="DESELECT")
    objs = [o for o in objs if o is not None]
    for o in objs:
        o.select_set(True)
    bpy.context.view_layer.objects.active = objs[0]

    kwargs = dict(
        filepath=path,
        export_format="GLB",
        use_selection=True,
        export_yup=True,
        export_apply=not animations,
        export_normals=True,
        export_tangents=False,
        export_materials="EXPORT",
        export_cameras=False,
        export_lights=False,
        export_extras=False,
        export_texcoords=True,
    )
    if animations:
        kwargs.update(
            export_animations=True,
            export_animation_mode="ACTIONS",
            export_skins=True,
            export_def_bones=False,
            export_bake_animation=False,
            export_optimize_animation_size=True,
            export_force_sampling=False,
            export_frame_range=False,
            export_anim_slide_to_zero=False,
        )
    else:
        kwargs.update(export_animations=False, export_skins=False)

    bpy.ops.export_scene.gltf(**kwargs)
    size = os.path.getsize(path)
    return {"file": filename, "path": path, "kb": round(size / 1024.0, 1)}


def report(entries):
    total = sum(e["kb"] for e in entries)
    lines = ["%-26s %8.1f KB" % (e["file"], e["kb"]) for e in entries]
    lines.append("%-26s %8.1f KB" % ("TOTAL", total))
    return "\n".join(lines)
