import { FIREARM_MIN_AGE, type WeaponDef, type WeaponId } from './WeaponDefinition';

/**
 * Four entries, and one of them is your hands.
 *
 * The numbers are balanced against a single question: **how many shots does a
 * calm person need to stop somebody, and how many does a panicking one waste?**
 * Composure is 0..1 and an unarmed shove takes 0.34, so three shoves settle an
 * ordinary argument. That is the yardstick everything else is measured against.
 *
 * | | Shots to stop, point-blank | At full range |
 * | --- | --- | --- |
 * | shove | 3 | n/a |
 * | pistol | 2 | 3 |
 * | shotgun | 1 | 3 |
 * | carbine | 2 | 2 |
 *
 * The shotgun is the only one-shot stopper and it is deliberately the worst
 * weapon in the game at anything past a corridor: eight pellets in a 9-degree
 * cone means most of them miss at twenty metres. The carbine is the opposite —
 * it barely cares about distance and is the loudest thing here, so using it
 * anywhere near people is how a quiet crime becomes a chase.
 *
 * **Nothing in this table is a real product.** The names are descriptive, the
 * models are generated by `scripts/blender/build_weapons.py`, and there is no
 * brand, marking or silhouette copied from anything.
 */

const UNARMED: WeaponDef = {
  id: 'unarmed',
  displayName: 'Hands',
  weaponClass: 'unarmed',
  magazine: 0,
  reserveMax: 0,
  ammoItemId: null,
  reloadSeconds: 0,
  fireInterval: 0.55,
  pellets: 1,
  // A shove is not aimed and does not benefit from aiming, but it must not be
  // *wider* aimed than hip-fired — `validateWeapon` refuses that.
  baseSpread: 0.05,
  aimSpread: 0.05,
  bloomPerShot: 0,
  bloomDecay: 1,
  recoil: { pitch: 0.004, yaw: 0.002, recover: 6 },
  range: 1.8,
  impact: 0.34,
  impactAtRange: 1,
  moveScale: 1,
  // Audible, barely. A scuffle carries about as far as a raised voice.
  loudness: 7,
  minAge: 0,
  conspicuous: false,
};

const PISTOL: WeaponDef = {
  id: 'pistol',
  displayName: 'Service pistol',
  weaponClass: 'sidearm',
  magazine: 12,
  reserveMax: 60,
  ammoItemId: 'ammo_pistol',
  reloadSeconds: 1.7,
  fireInterval: 0.28,
  pellets: 1,
  baseSpread: 0.075,
  aimSpread: 0.018,
  bloomPerShot: 0.012,
  bloomDecay: 0.9,
  recoil: { pitch: 0.022, yaw: 0.009, recover: 5.5 },
  range: 45,
  impact: 0.55,
  impactAtRange: 0.62,
  moveScale: 0.62,
  loudness: 90,
  minAge: FIREARM_MIN_AGE,
  conspicuous: true,
};

const SHOTGUN: WeaponDef = {
  id: 'shotgun',
  displayName: 'Break-action shotgun',
  weaponClass: 'shotgun',
  magazine: 2,
  reserveMax: 24,
  ammoItemId: 'ammo_shotgun',
  // Two shells, broken open and reloaded by hand. The slowest reload here, and
  // the reason a shotgun fight is decided by whether you counted.
  reloadSeconds: 2.9,
  fireInterval: 0.85,
  pellets: 8,
  baseSpread: 0.16,
  aimSpread: 0.085,
  bloomPerShot: 0.02,
  bloomDecay: 1.1,
  recoil: { pitch: 0.06, yaw: 0.02, recover: 4.5 },
  range: 22,
  // One pellet is weak; eight of them at contact range are not. Past a
  // corridor most of the cone misses, which is the whole character of it.
  impact: 0.15,
  impactAtRange: 0.25,
  moveScale: 0.55,
  loudness: 120,
  minAge: FIREARM_MIN_AGE,
  conspicuous: true,
};

const CARBINE: WeaponDef = {
  id: 'carbine',
  displayName: 'Compact carbine',
  weaponClass: 'carbine',
  magazine: 24,
  reserveMax: 96,
  ammoItemId: 'ammo_carbine',
  reloadSeconds: 2.2,
  fireInterval: 0.13,
  pellets: 1,
  baseSpread: 0.09,
  aimSpread: 0.012,
  // Fast enough that bloom is what stops you holding the trigger down.
  bloomPerShot: 0.016,
  bloomDecay: 0.75,
  recoil: { pitch: 0.017, yaw: 0.011, recover: 6.5 },
  range: 70,
  impact: 0.5,
  impactAtRange: 0.9,
  moveScale: 0.5,
  loudness: 140,
  minAge: FIREARM_MIN_AGE,
  conspicuous: true,
};

export const WEAPONS: readonly WeaponDef[] = [UNARMED, PISTOL, SHOTGUN, CARBINE];

const BY_ID = new Map(WEAPONS.map((w) => [w.id, w]));

export function weaponDef(id: string): WeaponDef | null {
  return BY_ID.get(id as WeaponId) ?? null;
}

/** Everything that is not your hands. What the adult gate actually covers. */
export const FIREARM_IDS: readonly WeaponId[] = WEAPONS.filter(
  (w) => w.weaponClass !== 'unarmed',
).map((w) => w.id);

/** Ammunition items the catalogue needs, so `Inventory` and this cannot drift. */
export const AMMO_ITEM_IDS: readonly string[] = WEAPONS.map((w) => w.ammoItemId).filter(
  (id): id is string => id !== null,
);
