/**
 * Every line of authored text, behind a key.
 *
 * The content files never hold a sentence. That is not ceremony: it is the
 * only arrangement in which "is anything missing a translation?" is a question
 * a *test* can answer, and `storyValidation` answers it by walking every quest
 * and asking this table for each key it names.
 *
 * One locale ships. `STRINGS` is the `en` table and `t()` falls back to the
 * key itself, so a missing entry shows up as `obj.q4_city_job.desk` on screen
 * rather than as an empty line — visibly wrong beats invisibly wrong. Adding a
 * second locale is another table and a lookup order; nothing above this file
 * needs to change, which is the point of doing it now rather than later.
 *
 * Voice: short, concrete, spoken. Nobody in this village makes a speech.
 */

export const STRINGS: Readonly<Record<string, string>> = {
  // -- chapters ------------------------------------------------------------
  'chapter.1': 'Five Things Left Behind',
  'chapter.2': 'First Pay',
  'chapter.3': 'The Road Test',
  'chapter.4': 'City Lights',
  'chapter.5': 'A Name of Your Own',
  'chapter.6': 'What the Road Costs',
  'chapter.7': 'The Last Horizon',

  // -- chapter 1 -----------------------------------------------------------
  'quest.q1_keepsakes.title': 'Five Things Left Behind',
  'quest.q1_keepsakes.summary': 'Five things have gone missing around the village. Most of them are yours.',
  'stage.q1_keepsakes.listen': 'Ask Eleni about the box',
  'hint.q1_keepsakes.listen': 'She keeps the school register, and everything else.',
  'obj.q1_keepsakes.ask': 'Talk to Eleni',
  'stage.q1_keepsakes.search': 'Find all five',
  'hint.q1_keepsakes.search': 'Under things, behind things, up where the wind put them.',
  'obj.q1_keepsakes.find': 'Keepsakes found',
  'obj.q1_keepsakes.hamid': 'Ask Hamid where to look',
  'stage.q1_keepsakes.bench': 'Take them to the bench',
  'hint.q1_keepsakes.bench': 'The one facing out.',
  'obj.q1_keepsakes.bench': 'Sit at the shore bench',
  'outcome.q1_keepsakes.done': 'You put the box back together',

  'quest.q1_the_road.title': 'The Road Out',
  'quest.q1_the_road.summary': 'An errand, a loaf, and the first time the road looks like it goes somewhere.',
  'stage.q1_the_road.errand': 'Fetch the bread',
  'hint.q1_the_road.errand': 'Maryam opens early.',
  'obj.q1_the_road.shop': 'Go to the grocery counter',
  'obj.q1_the_road.bread': 'Buy a loaf',
  'stage.q1_the_road.deliver': 'Take it to Gita',
  'hint.q1_the_road.deliver': 'The small house on the south bend.',
  'obj.q1_the_road.gita': 'Deliver the bread',
  'stage.q1_the_road.ride': 'Ride out to the bend',
  'hint.q1_the_road.ride': 'Far enough to see where it goes.',
  'obj.q1_the_road.ride': 'Ride the bicycle',
  'outcome.q1_the_road.done': 'You saw where the road went',

  // -- chapter 2 -----------------------------------------------------------
  'quest.q2_first_pay.title': 'First Pay',
  'quest.q2_first_pay.summary': 'Maryam needs hands. You need money that is yours.',
  'stage.q2_first_pay.ask': 'Ask Maryam for work',
  'hint.q2_first_pay.ask': 'Before the morning rush, if you can.',
  'obj.q2_first_pay.ask': 'Talk to Maryam',
  'stage.q2_first_pay.shift': 'Work the shift',
  'hint.q2_first_pay.shift': 'Boxes to the back, then the till.',
  'obj.q2_first_pay.shift': 'Complete a shop shift',
  'stage.q2_first_pay.spend': 'Spend some of it',
  'hint.q2_first_pay.spend': 'It is not real until you have spent a little.',
  'obj.q2_first_pay.buy': 'Buy a hot meal',
  'obj.q2_first_pay.save': 'Put something by as well',
  'outcome.q2_first_pay.done': 'You earned your first wage',

  'quest.q2_deliveries.title': 'The Round',
  'quest.q2_deliveries.summary': 'Liya has the parcel round and an opinion about how fast you are.',
  'stage.q2_deliveries.meet': 'Meet Liya',
  'hint.q2_deliveries.meet': 'She will be moving. She always is.',
  'obj.q2_deliveries.liya': 'Talk to Liya',
  'stage.q2_deliveries.round': 'Run the round',
  'hint.q2_deliveries.round': 'The farm, then the far house.',
  'obj.q2_deliveries.round': 'Complete the parcel round',
  'outcome.q2_deliveries.beat': 'You beat her time, and she noticed',
  'outcome.q2_deliveries.done': 'You finished the round',

  'quest.q2_the_bicycle.title': 'Something With Wheels',
  'quest.q2_the_bicycle.summary': 'Buy one, or make the dead one live. Tomás has views.',
  'stage.q2_the_bicycle.choose': 'Talk to Tomás',
  'hint.q2_the_bicycle.choose': 'He is under something, as usual.',
  'obj.q2_the_bicycle.tomas': 'Talk to Tomás',
  'stage.q2_the_bicycle.buy': 'Buy the bicycle',
  'hint.q2_the_bicycle.buy': 'Money now, riding today.',
  'obj.q2_the_bicycle.pay': 'Pay for the bicycle',
  'stage.q2_the_bicycle.fix': 'Fix the old one',
  'hint.q2_the_bicycle.fix': 'A kit, a bench, and an afternoon.',
  'obj.q2_the_bicycle.parts': 'Get a repair kit',
  'obj.q2_the_bicycle.bench': 'Work on it at the bench',
  'stage.q2_the_bicycle.ride': 'Take it out',
  'hint.q2_the_bicycle.ride': 'Properly out. Not to the end of the yard.',
  'obj.q2_the_bicycle.lap': 'Ride it in',
  'outcome.q2_the_bicycle.done': 'You had wheels of your own',

  // -- chapter 3 -----------------------------------------------------------
  'quest.q3_road_test.title': 'The Road Test',
  'quest.q3_road_test.summary': 'Tomás will teach you. The van is older than you are.',
  'stage.q3_road_test.lesson': 'Ask for the lesson',
  'hint.q3_road_test.lesson': 'He said seventeen. You are seventeen.',
  'obj.q3_road_test.ask': 'Talk to Tomás',
  'stage.q3_road_test.drive': 'Drive the route',
  'hint.q3_road_test.drive': 'Coast road, up and back.',
  'obj.q3_road_test.distance': 'Drive the route',
  'obj.q3_road_test.clean': 'Stop properly at the junction',
  'stage.q3_road_test.park': 'Put it away',
  'hint.q3_road_test.park': 'Between the lines, ideally.',
  'obj.q3_road_test.bay': 'Park in the bay',
  'outcome.q3_road_test.done': 'You passed, and they let you keep the paper',

  'quest.q3_mentor.title': 'Whose Advice',
  'quest.q3_mentor.summary': 'Three people think they know what you should do next.',
  'stage.q3_mentor.weigh': 'Hear them out, then decide',
  'hint.q3_mentor.weigh': 'You do not have to agree with any of them.',
  'obj.q3_mentor.trade': 'Hear what Tomás says',
  'obj.q3_mentor.school': 'Hear what Eleni says',
  'obj.q3_mentor.decide': 'Decide at the hall',
  'outcome.q3_mentor.trade': 'You chose the trade',
  'outcome.q3_mentor.school': 'You chose to keep studying',
  'outcome.q3_mentor.road': 'You chose the road',

  'quest.q3_the_crack.title': 'A Peg in the Field',
  'quest.q3_the_crack.summary': 'Somebody has been measuring Bashir’s field, and nobody asked him.',
  'stage.q3_the_crack.notice': 'Go and look',
  'hint.q3_the_crack.notice': 'The flat land by the road. The only flat land.',
  'obj.q3_the_crack.field': 'Go to the field',
  'obj.q3_the_crack.bashir': 'Talk to Bashir',
  'stage.q3_the_crack.ask': 'Ask who would want it',
  'hint.q3_the_crack.ask': 'Hamid has watched this road for forty years.',
  'obj.q3_the_crack.hamid': 'Talk to Hamid',
  'obj.q3_the_crack.peg': 'Look at the survey peg',
  'outcome.q3_the_crack.done': 'You saw it before anyone said it out loud',

  // -- chapter 4 -----------------------------------------------------------
  'quest.q4_departure.title': 'City Lights',
  'quest.q4_departure.summary': 'Eighteen. The bus goes at six, and it goes without you if you are late.',
  'stage.q4_departure.goodbyes': 'Say the goodbyes you mean to say',
  'hint.q4_departure.goodbyes': 'You can skip some. You will think about that.',
  'obj.q4_departure.home': 'Say goodbye to Eleni',
  'obj.q4_departure.friend': 'Say goodbye to Noor',
  'obj.q4_departure.elder': 'Say goodbye to Hamid',
  'stage.q4_departure.pack': 'Sleep one more night at home',
  'hint.q4_departure.pack': 'The bed you grew up in, for the last time as a resident.',
  'obj.q4_departure.sleep': 'Sleep at home',
  'stage.q4_departure.arrive': 'Get to the Old Market',
  'hint.q4_departure.arrive': 'It is louder than you expected.',
  'obj.q4_departure.city': 'Travel to the Old Market',
  'outcome.q4_departure.done': 'You left, and the road did go somewhere',

  'quest.q4_first_key.title': 'A Key of Your Own',
  'quest.q4_first_key.summary': 'One room, one window, and rent every seventh day.',
  'stage.q4_first_key.find': 'See the clerk',
  'hint.q4_first_key.find': 'Dawit has the lease and no small talk.',
  'obj.q4_first_key.clerk': 'Talk to Dawit',
  'stage.q4_first_key.sign': 'Move in',
  'hint.q4_first_key.sign': 'It is yours until you stop paying for it.',
  'obj.q4_first_key.sleep': 'Sleep there once',
  'obj.q4_first_key.decorate': 'Put something of yours in it',
  'outcome.q4_first_key.done': 'You had a door that locked behind you',

  'quest.q4_city_job.title': 'Something Steady',
  'quest.q4_city_job.summary': 'Yusuf is hiring. So is the garage. So is everyone, badly.',
  'stage.q4_city_job.hunt': 'Find work',
  'hint.q4_city_job.hunt': 'Ask more than one person.',
  'obj.q4_city_job.yusuf': 'Talk to Yusuf',
  'obj.q4_city_job.priya': 'Ask at the garage too',
  'stage.q4_city_job.work': 'Do a run',
  'hint.q4_city_job.work': 'Three drops, and the clock is running.',
  'obj.q4_city_job.courier': 'Complete a courier run',
  'stage.q4_city_job.settle': 'Register at the desk',
  'hint.q4_city_job.settle': 'Everyone working in the district is on a list somewhere.',
  'obj.q4_city_job.desk': 'Go to the police desk',
  'outcome.q4_city_job.done': 'You were somebody with a job and an address',

  // -- chapter 5 -----------------------------------------------------------
  'quest.q5_a_name.title': 'A Name of Your Own',
  'quest.q5_a_name.summary': 'Omar knows a faster way. Faster is not the only thing worth being.',
  'stage.q5_a_name.choose': 'Hear Omar out',
  'hint.q5_a_name.choose': 'He is not lying about the money.',
  'obj.q5_a_name.omar': 'Talk to Omar',
  'stage.q5_a_name.straight': 'Do it the long way',
  'hint.q5_a_name.straight': 'Two recovery calls, and put the rest aside.',
  'obj.q5_a_name.shifts': 'Complete recovery calls',
  'obj.q5_a_name.saved': 'Buy a scooter of your own',
  'stage.q5_a_name.shortcut': 'Do it Omar’s way',
  'hint.q5_a_name.shortcut': 'Two drops, no questions, and a quiet hour at the dock.',
  'obj.q5_a_name.run': 'Make the drops',
  'obj.q5_a_name.quiet': 'Meet the contact at the dock',
  'stage.q5_a_name.known': 'People know the name now',
  'hint.q5_a_name.known': 'Sana will have heard. She hears everything.',
  'obj.q5_a_name.cafe': 'Talk to Sana',
  'fail.q5_a_name.caught': 'Somebody was watching the dock. Try again another night.',
  'outcome.q5_a_name.done': 'You made a name, one way or another',

  'quest.q5_someone.title': 'Someone',
  'quest.q5_someone.summary': 'Evenings stop being something you get through.',
  'stage.q5_someone.evenings': 'Spend the evenings somewhere',
  'hint.q5_someone.evenings': 'Or do not. That is an answer too.',
  'obj.q5_someone.sana': 'Spend time with Sana',
  'obj.q5_someone.hana': 'Spend time with Hana',
  'obj.q5_someone.noor': 'Spend time with Noor',
  'obj.q5_someone.meal': 'Buy them dinner',
  'outcome.q5_someone.sana': 'You and Sana',
  'outcome.q5_someone.hana': 'You and Hana',
  'outcome.q5_someone.noor': 'You and Noor, after all this time',
  'outcome.q5_someone.alone': 'You kept your evenings',

  // -- chapter 6 -----------------------------------------------------------
  'quest.q6_the_offer.title': 'What the Road Costs',
  'quest.q6_the_offer.summary': 'The field by the road has a price now, and your name is on the letter.',
  'stage.q6_the_offer.letter': 'Read it, then go and see',
  'hint.q6_the_offer.letter': 'It is on your desk. It has been for a week.',
  'obj.q6_the_offer.read': 'Read the letter',
  'obj.q6_the_offer.home': 'Travel to the village',
  'stage.q6_the_offer.weigh': 'Find out what people want',
  'hint.q6_the_offer.weigh': 'Bashir first. He does not know yet.',
  'obj.q6_the_offer.bashir': 'Talk to Bashir',
  'obj.q6_the_offer.george': 'Ask George what happened last time',
  'obj.q6_the_offer.rosa': 'Ask Rosa how a petition works',
  'stage.q6_the_offer.protect': 'Stand in front of it',
  'hint.q6_the_offer.protect': 'Signatures, and money you will not get back.',
  'obj.q6_the_offer.petition': 'Gather support at the hall',
  'obj.q6_the_offer.fund': 'Put your own money in',
  'stage.q6_the_offer.exploit': 'Take the commission',
  'hint.q6_the_offer.exploit': 'It is legal. That is not the same as fine.',
  'obj.q6_the_offer.broker': 'Talk to Dawit',
  'obj.q6_the_offer.sign': 'Sign at the office',
  'stage.q6_the_offer.expose': 'Print what you found',
  'hint.q6_the_offer.expose': 'Three documents and someone who will say it out loud.',
  'obj.q6_the_offer.papers': 'Collect the documents',
  'obj.q6_the_offer.witness': 'Get George on the record',
  'obj.q6_the_offer.print': 'Print it',
  'stage.q6_the_offer.law': 'Do it through the law',
  'hint.q6_the_offer.law': 'Slower. Harder to argue with afterwards.',
  'obj.q6_the_offer.amina': 'Talk to Amina',
  'obj.q6_the_offer.file': 'File the objection',
  'obj.q6_the_offer.wait': 'Wait for the ruling',
  'stage.q6_the_offer.crime': 'Take the pegs out',
  'hint.q6_the_offer.crime': 'At night, and do not be there when it is noticed.',
  'obj.q6_the_offer.night': 'Get to the field after dark',
  'obj.q6_the_offer.pegs': 'Pull the survey pegs',
  'obj.q6_the_offer.away': 'Get clear',
  'fail.q6_the_offer.seen': 'Somebody saw you. Let it go quiet and come back.',
  'stage.q6_the_offer.settled': 'Tell him how it went',
  'hint.q6_the_offer.settled': 'However it went.',
  'obj.q6_the_offer.back': 'Talk to Bashir',
  'outcome.q6_the_offer.done': 'The field was settled, one way',

  // -- chapter 7 -----------------------------------------------------------
  'quest.q7_last_horizon.title': 'The Last Horizon',
  'quest.q7_last_horizon.summary': 'Twenty-five. Somebody asks where you live now and you have to answer.',
  'stage.q7_last_horizon.accounts': 'Read Eleni’s letter',
  'hint.q7_last_horizon.accounts': 'She still writes. Nobody else does.',
  'obj.q7_last_horizon.letter': 'Talk to Eleni',
  'obj.q7_last_horizon.partner': 'Sit with them a while',
  'stage.q7_last_horizon.decide': 'Go up the hill and decide',
  'hint.q7_last_horizon.decide': 'You can see both from there. That is the problem.',
  'obj.q7_last_horizon.stand': 'Stand on the hill',
  'outcome.q7.return': 'You went home',
  'outcome.q7.stay': 'You stayed',
  'outcome.q7.between': 'You kept both',

  // -- side tasks: village -------------------------------------------------
  'quest.s_neighbour_errand.title': 'Gita’s Errand',
  'quest.s_neighbour_errand.summary': 'One apple. She is very specific about the apple.',
  'stage.s_neighbour_errand.do': 'Fetch what Gita asked for',
  'hint.s_neighbour_errand.do': 'The good ones are at the front, apparently.',
  'obj.s_neighbour_errand.ask': 'Talk to Gita',
  'obj.s_neighbour_errand.buy': 'Buy an apple',
  'obj.s_neighbour_errand.back': 'Take it back',
  'outcome.s_neighbour_errand.done': 'Errand run',

  'quest.s_village_history.title': 'Forty Years on This Bench',
  'quest.s_village_history.summary': 'Hamid will tell you how the road got here. It takes a while.',
  'stage.s_village_history.do': 'Sit and listen',
  'hint.s_village_history.do': 'Do not check the time.',
  'obj.s_village_history.sit': 'Go to the bench',
  'obj.s_village_history.listen': 'Talk to Hamid',
  'obj.s_village_history.stay': 'Stay and hear it out',
  'outcome.s_village_history.done': 'You heard how the road got here',

  'quest.s_lost_camera.title': 'Noor’s Camera',
  'quest.s_lost_camera.summary': 'She swears she left it in the yard. She did not leave it in the yard.',
  'stage.s_lost_camera.do': 'Find the camera',
  'hint.s_lost_camera.do': 'Start where she says. Do not stop there.',
  'obj.s_lost_camera.noor': 'Talk to Noor',
  'obj.s_lost_camera.hunt': 'Search the yard',
  'obj.s_lost_camera.find': 'Find the camera',
  'outcome.s_lost_camera.done': 'You found it',

  'quest.s_shore_catch.title': 'Something for the Counter',
  'quest.s_shore_catch.summary': 'Maryam will take whatever the shore gives up.',
  'stage.s_shore_catch.do': 'Catch something and sell it',
  'hint.s_shore_catch.do': 'The waiting is the job.',
  'obj.s_shore_catch.fish': 'Catch a fish',
  'obj.s_shore_catch.sell': 'Sell it at the counter',
  'outcome.s_shore_catch.done': 'Sold at the counter',

  'quest.s_school_run.title': 'The Register',
  'quest.s_school_run.summary': 'Eleni needs two folders at the hall before it shuts.',
  'stage.s_school_run.do': 'Get the papers to the hall',
  'hint.s_school_run.do': 'Do not read them. She will know.',
  'obj.s_school_run.papers': 'Collect the folders',
  'obj.s_school_run.hall': 'Deliver them to the hall',
  'outcome.s_school_run.done': 'Filed on time',

  'quest.s_farm_hands.title': 'A Pair of Hands',
  'quest.s_farm_hands.summary': 'Bashir is a day behind and the weather is not waiting.',
  'stage.s_farm_hands.do': 'Work the field',
  'hint.s_farm_hands.do': 'Four rows. Your back will mention it.',
  'obj.s_farm_hands.field': 'Get to the field',
  'obj.s_farm_hands.work': 'Work the rows',
  'outcome.s_farm_hands.done': 'The field got done',

  'quest.s_workshop_hands.title': 'Hold This',
  'quest.s_workshop_hands.summary': 'Tomás needs someone to hold the light and not ask questions.',
  'stage.s_workshop_hands.do': 'Help in the workshop',
  'hint.s_workshop_hands.do': 'Mostly holding. Occasionally passing.',
  'obj.s_workshop_hands.yard': 'Get to the workshop',
  'obj.s_workshop_hands.hold': 'Help at the bench',
  'outcome.s_workshop_hands.done': 'The bolt came out eventually',

  'quest.s_noor_study.title': 'The Exam',
  'quest.s_noor_study.summary': 'Noor needs quiet and someone in the room. Mostly the second thing.',
  'stage.s_noor_study.do': 'Sit with her while she works',
  'hint.s_noor_study.do': 'Say nothing useful. That is the whole job.',
  'obj.s_noor_study.meet': 'Find Noor',
  'obj.s_noor_study.quiet': 'Stay while she studies',
  'outcome.s_noor_study.done': 'She passed',

  'quest.s_bike_rival.title': 'Liya’s Line',
  'quest.s_bike_rival.summary': 'From the junction to the hill. She has done it in four minutes.',
  'stage.s_bike_rival.do': 'Ride her line',
  'hint.s_bike_rival.do': 'She is not going to make it easy.',
  'obj.s_bike_rival.line': 'Talk to Liya',
  'obj.s_bike_rival.race': 'Ride the line',
  'outcome.s_bike_rival.done': 'You rode her line',

  'quest.s_hill_lookout.title': 'The Lookout',
  'quest.s_hill_lookout.summary': 'Somebody said you can see the city lights from up there on a clear night.',
  'stage.s_hill_lookout.do': 'Get up the hill and look',
  'hint.s_hill_lookout.do': 'Clear night helps.',
  'obj.s_hill_lookout.climb': 'Climb the hill',
  'obj.s_hill_lookout.look': 'Stay and look',
  'outcome.s_hill_lookout.done': 'You saw the lights',

  // -- side tasks: city ----------------------------------------------------
  'quest.s_market_stock.title': 'Delivery Day',
  'quest.s_market_stock.summary': 'Yusuf’s order came in three hours early and he is one person.',
  'stage.s_market_stock.do': 'Get the stock onto the shelves',
  'hint.s_market_stock.do': 'Back room first.',
  'obj.s_market_stock.yusuf': 'Talk to Yusuf',
  'obj.s_market_stock.boxes': 'Bring boxes through',
  'obj.s_market_stock.shelf': 'Stock the aisle',
  'outcome.s_market_stock.done': 'The order got put away',

  'quest.s_garage_hands.title': 'Priya’s Tow',
  'quest.s_garage_hands.summary': 'Somebody left a car where a car should not be.',
  'stage.s_garage_hands.do': 'Bring it in',
  'hint.s_garage_hands.do': 'Carefully. It is not yours.',
  'obj.s_garage_hands.priya': 'Talk to Priya',
  'obj.s_garage_hands.tow': 'Complete the recovery',
  'outcome.s_garage_hands.done': 'Recovered and booked in',

  'quest.s_paperwork.title': 'In Triplicate',
  'quest.s_paperwork.summary': 'Dawit has found a form that requires another form.',
  'stage.s_paperwork.do': 'File the forms',
  'hint.s_paperwork.do': 'There is an order. He will tell you it twice.',
  'obj.s_paperwork.dawit': 'Talk to Dawit',
  'obj.s_paperwork.forms': 'Collect the forms',
  'obj.s_paperwork.file': 'File them at the office',
  'outcome.s_paperwork.done': 'Filed, stamped, forgotten',

  'quest.s_cafe_shift.title': 'Covering the Morning',
  'quest.s_cafe_shift.summary': 'Sana is on her own and the machine is being difficult.',
  'stage.s_cafe_shift.do': 'Work the counter',
  'hint.s_cafe_shift.do': 'Four orders. Try not to break it further.',
  'obj.s_cafe_shift.sana': 'Talk to Sana',
  'obj.s_cafe_shift.serve': 'Serve at the counter',
  'outcome.s_cafe_shift.done': 'The morning got covered',

  'quest.s_city_history.title': 'What Was Here Before',
  'quest.s_city_history.summary': 'George remembers the square when it was not a square.',
  'stage.s_city_history.do': 'Walk it with him',
  'hint.s_city_history.do': 'He walks slowly and stops a lot.',
  'obj.s_city_history.george': 'Talk to George',
  'obj.s_city_history.walk': 'Walk to the square',
  'obj.s_city_history.listen': 'Hear him out',
  'outcome.s_city_history.done': 'You learned what was there before',

  'quest.s_night_shift.title': 'Night Run',
  'quest.s_night_shift.summary': 'Kenji needs notes across town and the clinic cannot spare anyone.',
  'stage.s_night_shift.do': 'Make the run',
  'hint.s_night_shift.do': 'It is quiet at this hour. Use that.',
  'obj.s_night_shift.kenji': 'Talk to Kenji',
  'obj.s_night_shift.run': 'Deliver to the clinic',
  'outcome.s_night_shift.done': 'The notes got there',

  'quest.s_petition.title': 'Door to Door',
  'quest.s_petition.summary': 'Rosa needs five signatures and has been refused nine times today.',
  'stage.s_petition.do': 'Knock on doors',
  'hint.s_petition.do': 'Most people say no. Some do not.',
  'obj.s_petition.rosa': 'Talk to Rosa',
  'obj.s_petition.doors': 'Get signatures',
  'outcome.s_petition.done': 'The petition got its names',

  'quest.s_courier_chain.title': 'The Chain',
  'quest.s_courier_chain.summary': 'Omar has a run that pays properly if you keep moving.',
  'stage.s_courier_chain.do': 'Run the chain',
  'hint.s_courier_chain.do': 'Do not stop to think about it.',
  'obj.s_courier_chain.omar': 'Talk to Omar',
  'obj.s_courier_chain.chain': 'Complete the courier run',
  'obj.s_courier_chain.fast': 'Cover the distance without stopping',
  'outcome.s_courier_chain.done': 'The chain held',

  'quest.s_dock_cargo.title': 'Down at the Dock',
  'quest.s_dock_cargo.summary': 'Marcel is short-handed and the tide is not negotiable.',
  'stage.s_dock_cargo.do': 'Shift the cargo',
  'hint.s_dock_cargo.do': 'Then put the van back where you found it.',
  'obj.s_dock_cargo.marcel': 'Talk to Marcel',
  'obj.s_dock_cargo.lift': 'Move the cargo',
  'obj.s_dock_cargo.park': 'Return the van',
  'outcome.s_dock_cargo.done': 'The tide got beaten',

  'quest.s_ines_errand.title': 'Inês Sends You Out',
  'quest.s_ines_errand.summary': 'Bread, and a message she does not want to send herself.',
  'stage.s_ines_errand.do': 'Run the errand',
  'hint.s_ines_errand.do': 'The message is the actual errand.',
  'obj.s_ines_errand.ines': 'Talk to Inês',
  'obj.s_ines_errand.shop': 'Buy a loaf',
  'obj.s_ines_errand.home': 'Take it to the market',
  'outcome.s_ines_errand.done': 'Delivered, message and all',

  // -- recorded choices ----------------------------------------------------
  'choice.ch2_bicycle.buy': 'You bought the bicycle',
  'choice.ch2_bicycle.fix': 'You rebuilt the old bicycle',
  'choice.ch3_mentor.trade': 'You took the trade',
  'choice.ch3_mentor.school': 'You stayed in school',
  'choice.ch3_mentor.road': 'You took the road',
  'choice.ch5_route.straight': 'You did it the long way',
  'choice.ch5_route.shortcut': 'You took the shortcut',
  'choice.ch5_someone.sana': 'You chose Sana',
  'choice.ch5_someone.hana': 'You chose Hana',
  'choice.ch5_someone.noor': 'You chose Noor',
  'choice.ch5_someone.alone': 'You stayed on your own',
  'choice.ch6_route.protect': 'You stood in front of the field',
  'choice.ch6_route.exploit': 'You took the commission',
  'choice.ch6_route.expose': 'You printed what you found',
  'choice.ch6_route.law': 'You went through the law',
  'choice.ch6_route.crime': 'You pulled the pegs',
  'choice.ch7_home.return': 'You went home',
  'choice.ch7_home.stay': 'You stayed in the city',
  'choice.ch7_home.between': 'You kept both',

  // -- the reel ------------------------------------------------------------
  'reel.chapter.1': 'Fifteen. Five things found.',
  'reel.chapter.2': 'Sixteen. First wage, first wheels.',
  'reel.chapter.3': 'Seventeen. A licence and a bad feeling about a field.',
  'reel.chapter.4': 'Eighteen. A key, a job, a city.',
  'reel.chapter.5': 'Twenty-one. People knew the name.',
  'reel.chapter.6': 'Twenty-four. The field was settled.',
  'reel.q1.allfive': 'All five, back in the box',
  'reel.q2.firstjob': 'First day behind a counter',
  'reel.q2.bicycle': 'The bicycle',
  'reel.q3.licence': 'Passed the road test',
  'reel.q3.peg': 'Found the survey peg',
  'reel.q4.arrived': 'Arrived in the Old Market',
  'reel.q4.apartment': 'One room, one window',
  'reel.q4.job': 'Steady work',
  'reel.q5.shortcut': 'Took the fast money',
  'reel.q5.sana': 'Sana',
  'reel.q5.hana': 'Hana',
  'reel.q5.noor': 'Noor, after all this time',
  'reel.q6.protect': 'Stood in front of the field',
  'reel.q6.exploit': 'Took the commission',
  'reel.q6.expose': 'Printed what you found',
  'reel.q6.law': 'Went through the law',
  'reel.q6.crime': 'Pulled the pegs at night',
  'reel.law.slipped': 'The record picked something up',
  'reel.side.history': 'Heard how the road got here',
  'reel.side.race': 'Rode Liya’s line',
  'reel.side.hill': 'Saw the city lights from the hill',

  // -- reel presentation ---------------------------------------------------
  'reel.title': 'A Life in Motion',
  'reel.subtitle': 'What did you become by 25?',
  'reel.section.choices': 'What you chose',
  'reel.section.work': 'What you did',
  'reel.section.people': 'Who was there',
  'reel.section.record': 'What the record says',
  'reel.section.things': 'What you kept',
  'reel.record.clean': 'Nothing on it',
  'reel.record.marked': 'A few things on it',
  'reel.record.bad': 'A long page',
  'reel.stat.money': 'Money',
  'reel.stat.jobs': 'Shifts worked',
  'reel.stat.vehicles': 'Vehicles owned',
  'reel.stat.keepsakes': 'Keepsakes',
  'reel.stat.friends': 'People who would answer',
  'reel.stat.community': 'Standing',
  'reel.empty': 'Nothing here yet.',
  'reel.birthday': 'You turned {age}',

  // -- endings -------------------------------------------------------------
  'ending.return_build_champion.title': 'Return and Build — The Field',
  'ending.return_build_champion.body':
    'The field is still a field. You farm the top half badly and Bashir says nothing about it, which is his way of saying a great deal. The village put your name on the hall board without asking. You have not taken it down.',
  'ending.return_build_witness.title': 'Return and Build — On the Record',
  'ending.return_build_witness.body':
    'What you printed is in a drawer in the city and a frame in the hall. People who did not like you at twenty-two nod at you now. It is not warmth exactly. It is closer to being counted on.',
  'ending.return_build_shadow.title': 'Return and Build — The Long Way Back',
  'ending.return_build_shadow.body':
    'You came home with a record and a van full of tools. Some doors took a year. Some took longer. Tomás handed you a spanner the first week and never mentioned any of it, and that is most of the story.',
  'ending.return_build_debt.title': 'Return and Build — Owed',
  'ending.return_build_debt.body':
    'You went back because there was nowhere else, and the village knew it. You get work. You do not get invited. The road is still there and this time you know exactly where it goes.',
  'ending.return_build_quiet.title': 'Return and Build — Quiet',
  'ending.return_build_quiet.body':
    'You took the house on the bend and a job that ends at five. Nobody writes about this. The bench still faces out, and most evenings you are on it.',

  'ending.stay_rise_magnate.title': 'Stay and Rise — The Office',
  'ending.stay_rise_magnate.body':
    'Two floors, a name on the glass, and a village you send money to instead of visiting. It worked. It is still working. Nobody from home calls unless something is wrong.',
  'ending.stay_rise_wanted.title': 'Stay and Rise — Watched',
  'ending.stay_rise_wanted.body':
    'You did well and you did it sideways. The money is real and so is the file with your name on it. You have learned which streets have cameras, which is a skill, and a sad one.',
  'ending.stay_rise_respected.title': 'Stay and Rise — Built Properly',
  'ending.stay_rise_respected.body':
    'You employ eleven people and you know all their children’s names. The village comes to you now, and you say yes more often than is strictly sensible. Eleni sends a letter every spring.',
  'ending.stay_rise_alone.title': 'Stay and Rise — Your Own Hours',
  'ending.stay_rise_alone.body':
    'A flat you like, work you are good at, and evenings that belong to nobody else. People keep asking when you will settle down. You keep not answering.',
  'ending.stay_rise_working.title': 'Stay and Rise — Still Going',
  'ending.stay_rise_working.body':
    'Rent paid, van running, someone to eat with on Sundays. It is not the life anyone writes a song about, and it is entirely yours.',

  'ending.live_between_bridge.title': 'Live Between Both — The Bridge',
  'ending.live_between_bridge.body':
    'Three days there, four days here, and a phone that will not stop. You are the person both places call when something needs carrying between them. It is exhausting and you are not going to stop.',
  'ending.live_between_courier.title': 'Live Between Both — The Route',
  'ending.live_between_courier.body':
    'You run the road for a living now — parcels out, produce back, the same eighty kilometres twice a week. You know every corner of it in the dark. It is the road, and it is yours.',
  'ending.live_between_restless.title': 'Live Between Both — Restless',
  'ending.live_between_restless.body':
    'A bed in each place and a bag that never quite unpacks. You tell people you have not decided. Ten years on you are saying the same thing, and it has started to sound like a decision.',

  // -- dialogue ------------------------------------------------------------
  'dlg.eleni_keepsakes.open': 'Your mother left a box with me. Five things in it. There are two now.',
  'dlg.eleni_keepsakes.what': 'What was in it?',
  'dlg.eleni_keepsakes.busy': 'Another time.',
  'dlg.eleni_keepsakes.what_a':
    'A paper plane. A toy boat. A wind chime. A camera that has never worked. And a star, off a tree, from before you were born.',
  'dlg.eleni_keepsakes.ask_where': 'Where would they have gone?',
  'dlg.eleni_keepsakes.ill_look': 'I will find them.',
  'dlg.eleni_keepsakes.where_a':
    'Children took them, wind took them, or the sea did. Ask Hamid. He watches everything and admits to nothing.',
  'dlg.eleni_keepsakes.go': 'I will start looking.',

  'dlg.maryam_errand.open': 'You are up early. Since you are here — Gita wants a loaf and I want my shop back.',
  'dlg.maryam_errand.take': 'I will take it to her.',
  'dlg.maryam_errand.take_a': 'Good. The south bend, the small house. Do not eat it on the way.',
  'dlg.maryam_errand.go': 'On my way.',

  'dlg.maryam_job.open': 'Sixteen, then. People start asking me for work at sixteen. Every year, like the weather.',
  'dlg.maryam_job.ask': 'Are you asking, or telling?',
  'dlg.maryam_job.ask_bold': 'You have been one pair of hands short since March.',
  'dlg.maryam_job.terms':
    'Boxes from the back, shelves, then the till. Forty-five for the shift and I do not pay for standing about.',
  'dlg.maryam_job.accept': 'I will take it.',
  'dlg.maryam_job.think': 'Let me think.',

  'dlg.liya_round.open': 'The round takes me forty minutes. It takes everyone else an hour and a half.',
  'dlg.liya_round.race': 'Forty, you say.',
  'dlg.liya_round.just_help': 'I only want to help.',
  'dlg.liya_round.terms': 'Farm first, then the far house. And do not cut across the field, he sees you.',
  'dlg.liya_round.go': 'Right.',

  'dlg.tomas_bicycle.open':
    'There is a bicycle behind the shed with no chain and a bent rim. There is also a new one in the shop.',
  'dlg.tomas_bicycle.ask_fix': 'What would the old one need?',
  'dlg.tomas_bicycle.ask_buy': 'And the new one?',
  'dlg.tomas_bicycle.fix_a':
    'A kit, an afternoon, and someone to hold it straight. It will be a better bicycle than the new one when it is done. Slower, though. To start with.',
  'dlg.tomas_bicycle.fix_yes': 'I will fix it.',
  'dlg.tomas_bicycle.back': 'Let me think about it.',
  'dlg.tomas_bicycle.buy_a': 'Money. That is all it needs. Nothing wrong with that, whatever I look like.',
  'dlg.tomas_bicycle.buy_yes': 'I will buy it.',

  'dlg.tomas_lesson.open': 'Seventeen. Right. The van is older than you and twice as stubborn.',
  'dlg.tomas_lesson.ready': 'I am ready.',
  'dlg.tomas_lesson.rules':
    'Two rules. Stop properly at the junction even when you can see it is empty. And put it back where you found it.',
  'dlg.tomas_lesson.go': 'Understood.',

  'dlg.mentor_choice.open': 'Three people have told you what to do this month. You have to pick one, or none.',
  'dlg.mentor_choice.trade': 'Tomás. The workshop.',
  'dlg.mentor_choice.school': 'Eleni. Keep studying.',
  'dlg.mentor_choice.road': 'Liya. The road.',
  'dlg.mentor_choice.later': 'Not today.',
  'dlg.mentor_choice.trade_a':
    'Then you learn on your knees under something, and in four years you can fix anything on this coast. That is not nothing.',
  'dlg.mentor_choice.school_a':
    'Then you keep the books open two more years. It buys you doors, and it costs you the two years. Both are true.',
  'dlg.mentor_choice.road_a':
    'Then you go now, and you learn it the fast way, and some of what you learn you would rather not have.',
  'dlg.mentor_choice.confirm': 'That is my answer.',
  'dlg.mentor_choice.back': 'Let me think again.',

  'dlg.bashir_field.open': 'Somebody has been walking my field with a tripod. Three days now. Did not knock.',
  'dlg.bashir_field.whose': 'Whose tripod?',
  'dlg.bashir_field.nothing': 'Probably nothing.',
  'dlg.bashir_field.whose_a':
    'City plates. That is all I know. It is the only flat ground between the road and the water, and I have known that all my life. Turns out somebody else worked it out.',
  'dlg.bashir_field.ill_ask': 'I will find out who.',

  'dlg.leaving.open': 'The bus is at six. You will be on it. Everyone is, eventually.',
  'dlg.leaving.thanks': 'Thank you. For the box, and the rest of it.',
  'dlg.leaving.quick': 'I should go.',
  'dlg.leaving.letter':
    'I will write. Not often — I am not sentimental — but I will write, and you will answer, and that is how this works.',
  'dlg.leaving.take_it': 'I will answer.',

  'dlg.dawit_lease.open': 'One room, third floor, window faces the wrong way. Next.',
  'dlg.dawit_lease.ask': 'What does it cost?',
  'dlg.dawit_lease.terms': 'A hundred and eighty every seven days. Paid when you sleep there. Miss it and I write it down.',
  'dlg.dawit_lease.sign': 'I will take it.',
  'dlg.dawit_lease.haggle': 'The window faces the wrong way, you said.',
  'dlg.dawit_lease.haggle_a': 'It does. That is why it is a hundred and eighty and not two hundred and twenty.',
  'dlg.dawit_lease.fine': 'Fine.',

  'dlg.yusuf_hire.open': 'You look like you have carried a box before. That is most of the interview.',
  'dlg.yusuf_hire.work': 'Are you hiring?',
  'dlg.yusuf_hire.village': 'I came in from the coast.',
  'dlg.yusuf_hire.village_a':
    'So did I. Nineteen years ago. Everyone here came in from somewhere and pretends they did not.',
  'dlg.yusuf_hire.terms': 'Runs, mostly. Three drops, and the clock matters more than I would like it to.',
  'dlg.yusuf_hire.start': 'When do I start?',

  'dlg.omar_shortcut.open': 'You are working very hard for very little. I have noticed. It is my job to notice.',
  'dlg.omar_shortcut.whats_in_it': 'Go on, then.',
  'dlg.omar_shortcut.not_interested': 'I am fine as I am.',
  'dlg.omar_shortcut.terms':
    'Two drops, no questions, an hour at the dock. Four times what the depot pays. I will not lie to you: if it goes wrong, it goes on your record and not mine.',
  'dlg.omar_shortcut.in': 'I am in.',
  'dlg.omar_shortcut.out': 'No.',
  'dlg.omar_shortcut.straight_a': 'Suit yourself. The slow way works too. It just takes the time it takes.',
  'dlg.omar_shortcut.confirm_straight': 'I will do it properly.',

  'dlg.someone.open': 'The evenings have started mattering. That is either good news or a problem.',
  'dlg.someone.sana': 'Sana, at the cafe.',
  'dlg.someone.hana': 'Hana.',
  'dlg.someone.noor': 'Noor. It was always going to be Noor.',
  'dlg.someone.alone': 'Nobody. Not yet.',

  'dlg.the_offer.open':
    'They have made me an offer. It is a good offer. That is what makes it hard — if it were a bad one I would have thrown it in the stove.',
  'dlg.the_offer.what_now': 'What do you want to happen?',
  'dlg.the_offer.sorry': 'I am sorry it came to you.',
  'dlg.the_offer.routes': 'There are ways to answer this. Some of them you can undo.',
  'dlg.the_offer.protect': 'We fight it in the open. Signatures, and my own money.',
  'dlg.the_offer.law': 'We do it through the law. Slowly, properly.',
  'dlg.the_offer.expose': 'I find out how they got the survey and I print it.',
  'dlg.the_offer.exploit': 'I broker it. He gets paid, and so do I.',
  'dlg.the_offer.crime': 'The pegs come out tonight and nobody sees me.',

  'dlg.last_horizon.open': 'Twenty-five. I have written you eleven letters and you have answered nine, which is better than most.',
  'dlg.last_horizon.read': 'Read it to me.',
  'dlg.last_horizon.pocket': 'I will read it later.',
  'dlg.last_horizon.ask': 'So. Where do you live now?',
  'dlg.last_horizon.return': 'Here. I am coming home.',
  'dlg.last_horizon.stay': 'There. My life is there now.',
  'dlg.last_horizon.between': 'Both. I am not choosing.',

  // -- cutscene captions ---------------------------------------------------
  'scene.cs_first_horizon.1': 'Five things, back where they started.',
  'scene.cs_first_horizon.2': 'The road goes north, and keeps going.',
  'scene.cs_the_road_out.1': 'Somebody must live at the other end of it.',
  'scene.cs_the_survey_peg.1': 'A survey peg. New.',
  'scene.cs_the_survey_peg.2': 'Straight across the only flat ground for a mile.',
  'scene.cs_leaving_the_village.1': 'It fits in one box, in the end.',
  'scene.cs_leaving_the_village.2': 'Eighteen. The bus is at six.',
  'scene.cs_a_name_of_your_own.1': 'People say the name now before you do.',
  'scene.cs_the_letter.1': 'Your name, on a letter about somebody else’s field.',
  'scene.cs_the_letter.2': 'They knew you would know who to ask.',
  'scene.cs_what_the_road_costs.1': 'However it went, you came and told him yourself.',
  'scene.cs_what_the_road_costs.2': 'The field, either way, is what it is now.',
  'scene.cs_the_last_horizon.1': 'Twenty-five.',
  'scene.cs_the_last_horizon.2': 'From up here you can see the whole of it.',
  'scene.cs_the_last_horizon.3': 'The village, and the road, and the lights past the headland.',
  'scene.cs_the_last_horizon.4': 'Grow up on one road. Choose the life beyond it.',
  'scene.cs_the_lookout.1': 'On a clear night, you can just make them out.',

  // -- ui ------------------------------------------------------------------
  'ui.journal.title': 'Journal',
  'ui.journal.main': 'Story',
  'ui.journal.side': 'Tasks',
  'ui.journal.none': 'Nothing on just now.',
  'ui.dialogue.continue': 'Continue',
  'ui.dialogue.leave': 'Leave it there',
  'ui.dialogue.skip': 'Skip',
  'ui.dialogue.history': 'Earlier',
  'ui.quest.started': 'New: {title}',
  'ui.quest.completed': 'Done: {title}',
  'ui.quest.failed': 'That did not work',
  'ui.quest.reward': 'Paid ${money}',
  'ui.credits.continue': 'Keep playing',
  'ui.ageing.on': 'Keep ageing',
  'ui.ageing.slow': 'Slow it down',
  'ui.ageing.frozen': 'Stop the clock',
};

/**
 * Look up a key, with `{placeholder}` substitution.
 *
 * Falls back to the key itself. A missing string should be *visible* — an
 * empty label reads as a layout bug and gets triaged as one, while
 * `obj.q4_city_job.desk` on screen names the exact thing to add.
 */
export function t(key: string, params?: Readonly<Record<string, string | number>>): string {
  const raw = STRINGS[key] ?? key;
  if (!params) return raw;
  return raw.replace(/\{(\w+)\}/g, (whole, name: string) =>
    name in params ? String(params[name]) : whole,
  );
}

export function hasString(key: string): boolean {
  return key in STRINGS;
}
