/**
 * The page's half of the service worker: registration, and the two banners.
 *
 * Small on purpose — it is eager code on a budget with 5 kB of headroom, and
 * everything interesting is in `dist/sw.js` (generated by
 * `scripts/vite-plugin-pwa.mjs`).
 *
 * ## The update flow, and why the player is asked
 *
 * A waiting worker is **not** activated automatically. The reason is the one
 * the brief names: a worker that takes over mid-session can pair last week's
 * JavaScript with this week's save schema, and the player loses a run. So a
 * new build waits, this file offers "Update", and only then does the page post
 * `LH_SKIP_WAITING` and reload — code and schema arriving together, at a
 * moment the player chose, which is also a moment they are not mid-mission.
 *
 * ## Registration timing
 *
 * After `load`, never before. Registration competes for bandwidth with the
 * 1.4 MB of GLB the loading screen is waiting on, and a service worker that
 * makes the first visit slower to help the second one is a bad trade — the
 * first visit is the only one some players take.
 */

const $ = (id: string): HTMLElement | null => document.getElementById(id);

let registration: ServiceWorkerRegistration | null = null;

export type SwState = 'unsupported' | 'registering' | 'ready' | 'update-waiting' | 'failed';

let state: SwState = 'unsupported';

/** Test-facing. */
export function swState(): SwState {
  return state;
}

/** Test-only: forget the registration so a suite can drive this twice. */
export function resetServiceWorkerForTest(): void {
  registration = null;
  state = 'unsupported';
}

function showBanner(id: string, show: boolean): void {
  const el = $(id);
  if (el) el.hidden = !show;
}

function offerUpdate(reg: ServiceWorkerRegistration): void {
  state = 'update-waiting';
  showBanner('swUpdate', true);

  const btn = $('swUpdateGo') as HTMLButtonElement | null;
  if (!btn) return;
  btn.onclick = () => {
    btn.disabled = true;
    // Reload when the new worker takes control, rather than immediately: a
    // reload racing the activation reloads onto the *old* worker and the
    // update appears not to have worked.
    navigator.serviceWorker.addEventListener('controllerchange', () => location.reload(), {
      once: true,
    });
    reg.waiting?.postMessage({ type: 'LH_SKIP_WAITING' });
  };

  const later = $('swUpdateLater') as HTMLButtonElement | null;
  if (later) later.onclick = () => showBanner('swUpdate', false);
}

function watchForUpdate(reg: ServiceWorkerRegistration): void {
  if (reg.waiting && navigator.serviceWorker.controller) {
    offerUpdate(reg);
    return;
  }
  reg.addEventListener('updatefound', () => {
    const next = reg.installing;
    if (!next) return;
    next.addEventListener('statechange', () => {
      // `controller` is null on the very first install, and that is not an
      // update — there is nothing to replace and nothing to warn about.
      if (next.state === 'installed' && navigator.serviceWorker.controller) offerUpdate(reg);
    });
  });
}

function watchConnectivity(): void {
  const sync = (): void => showBanner('swOffline', !navigator.onLine);
  window.addEventListener('online', sync);
  window.addEventListener('offline', sync);
  sync();
}

/**
 * Register, if the browser and the context allow it.
 *
 * Service workers need a secure context. `localhost` counts, a plain-HTTP
 * staging host does not, and a `file://` open of `dist/` does not either —
 * all three are ordinary ways to run this game, so a missing worker is a
 * normal state rather than an error. The game is fully playable without one;
 * it simply is not offline-capable.
 */
export function registerServiceWorker(): void {
  // Check the *value*, not just the key. `'serviceWorker' in navigator` is
  // true for a property that exists and is undefined, which is exactly what a
  // browser with the API stubbed out looks like — and the guard then falls
  // through to `navigator.serviceWorker.register` and throws a TypeError
  // during boot. Firefox's private-browsing mode is the realistic case: the
  // property is present and unusable.
  if (!navigator.serviceWorker || !window.isSecureContext) {
    state = 'unsupported';
    return;
  }

  watchConnectivity();
  state = 'registering';

  const go = (): void => {
    // Relative, so the game works when deployed in a subdirectory as well as
    // at a domain root — which is the difference between kanbanstudios.ae/game
    // and game.kanbanstudios.ae, and both are on the table.
    navigator.serviceWorker
      .register(new URL('sw.js', document.baseURI), { scope: './' })
      .then((reg) => {
        registration = reg;
        state = 'ready';
        watchForUpdate(reg);
      })
      .catch((err) => {
        // Never fatal. Log it and carry on: an uninstallable worker is a
        // worse offline story, not a broken game.
        state = 'failed';
        console.warn('[LastHorizon] service worker registration failed', err);
      });
  };

  // **Check `readyState` first — a `load` listener added after `load` has
  // fired never runs.**
  //
  // The first version of this waited unconditionally on the event, and the
  // call site is at the end of `boot()`, which is `async` and awaits ~1.4 MB
  // of GLB. `load` fires long before that resolves, so the listener was always
  // registered too late and the worker was **never installed at all** — no
  // offline play, no update prompt, and no error to say so.
  //
  // The deferral itself is still right: registration should not compete for
  // bandwidth with the assets the loading screen is waiting on. It is just
  // that by the time this is called, the deferral has already happened.
  if (document.readyState === 'complete') go();
  else window.addEventListener('load', go, { once: true });
}

/** Test-facing: ask the browser to look for a new build. */
export async function checkForUpdate(): Promise<void> {
  await registration?.update();
}
