import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Plugin } from 'vite';

/**
 * Generates `sw.js` and `manifest.webmanifest` at build time.
 *
 * ## Why this is not Workbox
 *
 * See `docs/adr/0003-hand-written-service-worker.md`. In short: the strategies
 * below *are* Workbox's — precache-on-install, cache-first for immutable
 * hashed assets, network-first for the navigation shell,
 * stale-while-revalidate for on-demand art — and they are about eighty lines
 * when you already know which files are which. What Workbox would add on top
 * is a dependency, a build integration, and a generated worker whose
 * versioning is keyed on the build rather than on **the save schema**, which
 * is the one thing this game actually needs it keyed on.
 *
 * ## The failure this is built around
 *
 * Not "the player is offline". It is *a stale worker serving last week's
 * JavaScript to this week's save file.* A service worker outlives the page
 * that installed it, so without care a returning player gets cached code that
 * predates a save migration, reads a v5 save with a v4 reader, and loses a
 * run. Three things prevent that:
 *
 * 1. The cache name carries the **save schema version** as well as the build.
 *    A schema bump orphans every previous cache by construction.
 * 2. `activate` deletes every cache that is not the current name, so there is
 *    never more than one generation resident.
 * 3. A new worker **never activates under a running game**. It waits, the page
 *    offers the player an update, and `skipWaiting` happens only when they
 *    accept — at which point the page reloads, so code and schema arrive
 *    together. Auto-updating mid-session is exactly how the mixing happens.
 */

/** Bumped when the *cache layout* changes, independent of the game version. */
const SW_FORMAT = 1;

/**
 * What a first visit should be able to replay offline: the shell, and enough
 * art to stand the village up.
 *
 * Deliberately **not** everything. The brief's rule is to cache the shell and
 * the first village experience and to runtime-cache the rest, so a player who
 * opens the link on a phone does not silently download Rapier's 2.2 MB, the
 * story chunk, the city, the weapons or the aeroplane before they have
 * decided they like the game. Those arrive through `stale-while-revalidate`
 * the first time they are genuinely needed, and are then available offline.
 */
const PRECACHE_ASSET_PREFIXES = ['index-', 'three-', 'gsap-', 'bvh-'];

const PRECACHE_MODELS = [
  'buildings.glb',
  'player.glb',
  'nature.glb',
  'props.glb',
  'collectibles.glb',
];

function swSource({ cacheName, precache }: { cacheName: string; precache: string[] }): string {
  return `/* Generated by scripts/vite-plugin-pwa.mjs — do not edit dist/sw.js. */
const CACHE = ${JSON.stringify(cacheName)};
const PRECACHE = ${JSON.stringify(precache, null, 2)};

/** Hashed build output is immutable: same URL, same bytes, forever. */
const isImmutable = (url) => /\\/assets\\/[^/]+-[A-Za-z0-9_-]{8}\\.(?:js|css)$/.test(url.pathname);

/** Art fetched on demand — models and audio. Worth keeping once seen. */
const isOnDemandAsset = (url) => /\\.(?:glb|mp3|png|ktx2|basis)$/.test(url.pathname);

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // Individually rather than \`addAll\`, which rejects the whole install if
      // any single request fails. A missing optional asset must not leave the
      // player with no offline shell at all.
      await Promise.all(
        PRECACHE.map((u) =>
          cache.add(new Request(u, { cache: 'reload' })).catch(() => undefined),
        ),
      );
      // Deliberately no skipWaiting: see the module comment. A new worker
      // waits until the player accepts the update.
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names.filter((n) => n !== CACHE && n.startsWith('lh-')).map((n) => caches.delete(n)),
      );
      await self.clients.claim();
    })(),
  );
});

self.addEventListener('message', (event) => {
  // The only way this worker ever takes over early, and it happens because a
  // player pressed a button that also reloads the page.
  if (event.data && event.data.type === 'LH_SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  // Never touch another origin. Nothing in this game loads one, and a worker
  // that caches third-party responses is a worker that can serve a stale one.
  if (url.origin !== self.location.origin) return;

  // The shell. Network-first so a deployed update is picked up on the next
  // visit, cache as the offline fallback.
  if (req.mode === 'navigate') {
    event.respondWith(
      (async () => {
        try {
          const fresh = await fetch(req);
          const cache = await caches.open(CACHE);
          cache.put('index.html', fresh.clone());
          return fresh;
        } catch {
          const cached = await caches.match('index.html');
          return cached ?? Response.error();
        }
      })(),
    );
    return;
  }

  // Immutable build output. Cache-first: if the URL is in the cache it is
  // correct, because the hash changed when the bytes did.
  if (isImmutable(url)) {
    event.respondWith(
      (async () => {
        const cached = await caches.match(req);
        if (cached) return cached;
        const fresh = await fetch(req);
        if (fresh.ok) (await caches.open(CACHE)).put(req, fresh.clone());
        return fresh;
      })(),
    );
    return;
  }

  // Models and audio. Stale-while-revalidate: instant on a repeat visit, and
  // quietly refreshed for the next one.
  if (isOnDemandAsset(url)) {
    event.respondWith(
      (async () => {
        const cached = await caches.match(req);
        const network = fetch(req)
          .then(async (fresh) => {
            if (fresh.ok) (await caches.open(CACHE)).put(req, fresh.clone());
            return fresh;
          })
          .catch(() => undefined);
        return cached ?? (await network) ?? Response.error();
      })(),
    );
    return;
  }

  // Everything else: network, falling back to whatever was cached.
  event.respondWith(fetch(req).catch(async () => (await caches.match(req)) ?? Response.error()));
});
`;
}

function manifestSource({ version }: { version: string }): string {
  return JSON.stringify(
    {
      name: 'Last Horizon — A Life in Motion',
      short_name: 'Last Horizon',
      description:
        'Grow up on one road. Choose the life beyond it. A cozy life-and-crime sandbox that runs in a browser.',
      id: '/',
      start_url: './',
      scope: './',
      display: 'fullscreen',
      // A landscape game. `display_override` lets a desktop install drop the
      // browser chrome entirely where the platform supports it.
      display_override: ['window-controls-overlay', 'fullscreen', 'standalone'],
      orientation: 'landscape',
      background_color: '#cfe3ee',
      theme_color: '#cfe3ee',
      categories: ['games'],
      version,
      icons: [
        // One source image at 512, declared for both sizes and as `maskable`.
        // Shipping three near-identical PNGs to satisfy a lint rule would cost
        // real bytes against a real budget for no visible difference.
        { src: './icon.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
        { src: './icon.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
      ],
    },
    null,
    2,
  );
}

export interface PwaOptions {
  readonly version: string;
  readonly build: string;
  readonly saveSchema: number;
}

export function lastHorizonPwa(opts: PwaOptions): Plugin {
  let outDir = 'dist';

  return {
    name: 'lh-pwa',
    apply: 'build',

    configResolved(config): void {
      outDir = config.build.outDir;
    },

    /**
     * `writeBundle` rather than `generateBundle`: the precache list has to
     * name files that exist, and `public/` is copied after the bundle is
     * generated. Building the list from the bundle alone would omit every
     * model and the icon.
     */
    writeBundle(_options, bundle): void {
      const emitted = Object.keys(bundle);

      const shell = emitted
        .filter(
          (f) =>
            (f.endsWith('.js') || f.endsWith('.css')) &&
            PRECACHE_ASSET_PREFIXES.some((p) => f.replace('assets/', '').startsWith(p)),
        )
        .map((f) => `./${f}`);

      const precache = [
        './',
        './index.html',
        './manifest.webmanifest',
        './icon.png',
        ...shell,
        ...PRECACHE_MODELS.map((m) => `./assets/models/${m}`),
      ];

      const cacheName = `lh-${opts.version}-${opts.build}-s${opts.saveSchema}-f${SW_FORMAT}`;

      writeFileSync(join(outDir, 'sw.js'), swSource({ cacheName, precache }), 'utf8');
      writeFileSync(
        join(outDir, 'manifest.webmanifest'),
        manifestSource({ version: opts.version }),
        'utf8',
      );
    },
  };
}

/**
 * Read `CURRENT_SAVE_VERSION` out of the schema rather than restating it.
 *
 * A second copy of this number is a second thing to forget to bump, and the
 * cost of forgetting is the precise failure the worker exists to prevent — a
 * cached build serving a reader older than the save it is handed.
 */
export function currentSaveVersion(schemaPath = 'src/save/SaveSchema.ts'): number {
  const src = readFileSync(schemaPath, 'utf8');
  const m = /CURRENT_SAVE_VERSION\s*=\s*(\d+)/.exec(src);
  if (!m) throw new Error('could not read CURRENT_SAVE_VERSION from ' + schemaPath);
  return Number(m[1]);
}
